{% set xorg_name = "makedepend" %}
{% set xorg_category = "util" %}
{% set name = "xorg-" ~ xorg_name %}
{% set version = "1.0.9" %}
{% set sha256 = "92d0deb659fff6d8ddbc1d27fc4ca8ceb2b6dbe15d73f0a04edc09f1c5782dd4" %}
{% set am_version = "1.16" %} # keep synchronized with build.sh

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.x.org/releases/individual/{{ xorg_category }}/{{ xorg_name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}
  patches:
    - msvc.patch  # [win]

build:
  number: 0

requirements:
  build:
    - m2-autoconf  # [win]
    - m2-automake{{ am_version }}  # [win]
    - m2-grep  # [win]
    - m2-libtool  # [win]
    - m2-m4  # [win]
    - m2-make  # [win]
    - m2-pkg-config  # [win]
    - make  # [not win]
    - pkg-config  # [not win]
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - xorg-util-macros  # [win]
    - xorg-xorgproto
  run:

test:
  commands:
    - '[[ "`makedepend 2>&1`" == *"makedepend: error:  [mM]akefile is not present" ]]'  # [not win and build_platform == target_platform]
    - test -f ${PREFIX}/bin/makedepend  # [not win]

about:
  home: https://www.x.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'The X.org incarnation of the X11 makedepend utility.'

extra:
  recipe-maintainers:
    - epruesse
    - pkgw
    - zklaus
