{% set xorg_name = "makedepend" %}
{% set xorg_category = "util" %}
{% set name = "xorg-" ~ xorg_name %}
{% set version = "1.0.8" %}
{% set sha256 = "bfb26f8025189b2a01286ce6daacc2af8fe647440b40bb741dd5c397572cba5b" %}
{% set am_version = "1.15" %} # keep synchronized with build.sh

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.x.org/releases/individual/{{ xorg_category }}/{{ xorg_name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - m2-autoconf  # [win]
    - m2-automake{{ am_version }}  # [win]
    - m2-libtool  # [win]
    - m2w64-pkg-config  # [win]
    - make
    - pkg-config  # [not win]
    - posix  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - xorg-util-macros  # [win]
    - xorg-xorgproto
  run:

test:
  commands:
    - 'test "`makedepend 2>&1`" = "makedepend: error:  [mM]akefile is not present"'  # [not win]

about:
  home: https://www.x.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'The X.org incarnation of the X11 makedepend utility.'

extra:
  recipe-maintainers:
    - epruesse
    - pkgw
    - zklaus
