appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: CIihKeosmX6wEHZr+FWExK6zc7WYuGSxf0DMsJR0HMCLYS/NNelNUSy1YshoEl/BHEIfTL0pCAIa8Ac/bJAE0aShEctKeaYldVdTOAyzx/btebhx1edLhW2vwMIwCKl/EU4sPOp0zFgdRYsaQZHZ2avxp2xLNV5EVnDnaSVgeKvCA/XXIMiRtuguFdd+cU60gKNkK52e2Xk4AMwhgh4C7VFql9dcnqGhOnwSB7cxDYYvNYbxnKSWe40yld27POkXaPKg7RiWDRChEdWWa9wzsxuo42ukY51/m6QlS/h9Ukqf+ghgxZxNKSaIYO3DMTs+nmh5nS6aODs/72xVZHaErBz8gQ8z2QUlswHXNxg9LcDIARw3HnR9UqiyI6NauK3mnlIROtComraRcxOV4J05XmD4o0W1ScB53Aw9K5p1n0QlMTXcP8BKcpVF5OhmH4p/Ph35oIxAzaZdkPUeF13iqTHST+l4zZL2R1E71FbaPC8BVJapc/ALnIwZ+EA2cJKEnsXx5mYZKwH7x8tRVVFdotUX3XtVB+LZShY4EWvI5GLAb9FFzPG2rrUrr1nUHbcF32vof4nHQQs7JUex+3RSGLjjPmzqSqUY526ZpJUDoowqrpixQVpSTF6LCKI1bC6r0BNkZY6AHL6QCgTU193NozK7Es4TorarrGkiTFgIuhg=}
provider:
  win: azure
conda_forge_output_validation: true
