travis:
  secure:
    BINSTAR_TOKEN: vHOsO+A/2JHcfGo2QXdIqGtOMunm7wIdR1pTlvG0N/3OzLbM2UcqbtqLQNdLTRKh6Su34DpG26txh3rCIQq5hBRdnOBqKuOB+IDETf09GHiY02x31rST7DDZeYsYGh6V5T4uaz2vpkbds26fIuM4gMgASrdAE7qfXX6ubwQ87xNTxOl0BenOBmTSYHIv0j9OVydWAgEGtgjm3SJAcRaTjkYGLVL7SkCDfLH3U+D024Isy0hXjs4gNAd/OxqUiYuj7y4rr73rcQZr6vqTq9+xjNRNvxQLS1bh7Xw2z4Cgy6bpnrZSw0cy7Lk6VEx2m5KGEoIYIm6RmSkHasD3AVyPkTP/5eYkGXaarFjmj3YzbHGLn/TGEVBna0odmb6BEjF1DG/qtnFWUv6Z0wd8PjhEQC3jr3uX2fJWMIXYiIIIqVAEVXdrkyGxKLKaurbV3L7bcYdOIg5BFD0TLDLImiXvQUlG42hBykh87PhKirOZZuogl4cwNDvy9lMM8gzLxB4NNdnxinBhjD7oarMeKE88PvZ45sju4X537YN/M2Zmeh2a+3WCmIfdEJnFgqwN0ZKhYLIRt43L/ZcFStVik6xOObGQAk+lDUfNpPoLzQDjyT3nT4mvoDGtaF8BZl64OQzyfLIelQn+BgoBl2iQHmo0IqutURWgqzrOQZhU1lycRjE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
